name: RELEASE

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - uix
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting for sonar
          fetch-depth: 0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            - name: Cache local Maven repository

      - name: Cache local NPM repository
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install zopfli
        run: sudo apt-get install -y zopfli

      - name: Verify signature NuvlaBox script
        run: ./.travis/verify_signature.sh

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set PR commit SHA in environment variables useful for build version
        if: github.event_name == 'pull_request'
        run: echo "GITHUB_PR_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

#      - name: Setup Sonar Scanner
#        uses: warchant/setup-sonar-scanner@v3
#        with:
#          version: 4.6.2.2472
#
#      - name: Run Sonar Scanner
#        env:
#          # provide GITHUB_TOKEN to get access to secrets.SONARQUBE_TOKEN
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        working-directory: code
#        run: sonar-scanner
#          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
#          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
#
#      - name: SonarQube Quality Gate check
#        uses: sonarsource/sonarqube-quality-gate-action@v1.0.0
#        # Force to fail step after specific time
#        timeout-minutes: 5
#        with:
#          scanMetadataReportFile: code/.scannerwork/report-task.txt
#        env:
#          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

#      - uses: s4u/maven-settings-action@v2.2.0
#        with:
#          githubServer: false
#          override: true
#          servers: |
#            [{
#                "id": "docker.io",
#                "username": "${{ secrets.SIXSQ_DOCKER_USERNAME }}",
#                "password": "${{ secrets.SIXSQ_DOCKER_PASSWORD }}"
#            }]

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      #      - name: Build with Maven
      #        env:
      #          TRAVIS_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      #          TRAVIS_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
      #          TRAVIS_BUILD_NUMBER: ${{ github.run_id }}
      #          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #        run: mvn deploy

      - name: Set PROJECT_VERSION environment variable
        working-directory: code
        run: echo "PROJECT_VERSION=`lein update-in :version pr -- version | cut -d '"' -f 2`" >> $GITHUB_ENV

      - name: Clean and install npm deps
        working-directory: code
        run: npm ci --legacy-peer-deps

      - name: Build with leinengen
        working-directory: code
        run: lein install

      - name: Unpack jar artifact
        run: |
          mkdir -p container/target/dependency/ui
          unzip code/target/*.jar -d container/target/dependency/ui

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SIXSQ_DOCKER_USERNAME }}
          password: ${{ secrets.SIXSQ_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./container
          file: container/Dockerfile
          build-args: |
            GIT_BRANCH=${{ github.head_ref || github.ref_name }}
            GIT_BUILD_TIME=$(date --utc +%FT%T.%3NZ)
            GIT_COMMIT_ID=${{ github.sha }}
            PACKAGE_TAG=${{ env.PROJECT_VERSION }}
            GITHUB_RUN_NUMBER=${{ github.run_number }}
            GITHUB_RUN_ID=${{ github.run_id }}
            PROJECT_URL=${{ github.server_url }}/${{ github.repository }}
            PACKAGE_NAME=alesixsq/nuvla/ui
          push: true
          tags: >
            alesixsq/nuvla/ui:${{ env.PROJECT_VERSION }}
# PACKAGE_TAG=${{ needs.trigger-release.outputs.tag_name }}

  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
